name: Stdlib dependency update
 
on:
  workflow_dispatch:
  push:
    paths:
    - 'build.gradle'
 
jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Initiating repository event
        run: |
          curl -u ${{ secrets.BALLERINA_BOT_USERNAME }} -X POST \
          https://api.github.com/repos/ballerina-platform/ballerina-standard-library/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: token ${{ secrets.BALLERINA_BOT_TOKEN }}' \
          --data '{
            "event_type": "dependency-update"
          }'
